# 开发环境
# 发布端口
server:
  port: 8082

spring:
  application:
    name: user-service
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.164.100:3306/nengyuyue?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: hao19990519
  cloud:
    nacos:
      server-addr: 192.168.164.100:8848

#日志配置
logging:
  level:
    com.hao: debug

