# 开发环境
# 发布端口
server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.164.100:3306/nengyuyue?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: hao19990519
  redis:
    host: 192.168.164.100
    port: 6379
    password: hao19990519
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# RocketMQ
rocketmq:
  name-server: 192.168.164.100:9876
  producer:
    group: group1

#日志配置
logging:
  level:
    com.hao: debug

